export type WebApi =
 | 'Accelerometer'
 | 'AmbientLightSensor'
 | 'BarcodeDetector'
 | 'Battery'
 | 'Bluetooth'
 | 'BroadcastChannel'
 | 'Clipboard'
 | 'ContactPicker'
 | 'ContentIndex'
 | 'CookieStore'
 | 'DigitalGoods'
 | 'EyeDropper'
 | 'File'
 | 'FileSystemHandle'
 | 'Fullscreen'
 | 'Gamepad'
 | 'Geolocation'
 | 'Gyroscope'
 | 'GravitySensor'
 | 'Gyroscope'
 | 'History'
 | 'Sanitizer'
 | 'ImageCapture'
 | 'IndexedDB'
 | 'IntersectionObserver'
 | 'LargestContentfulPaint'
 | 'LayoutShift'
 | 'LinearAccelerationSensor'
 | 'Magnetometer'
 | 'Connection'
 | 'Notification'
 | 'OrientationSensor'
 | 'PaymentRequest'
 | 'Performance'
 | 'Permissions'
 | 'PictureInPictureWindow'
 | 'ReportingObserver'
 | 'Orientation'
 | 'WakeLock'
 | 'Selection'
 | 'Storage'
 | 'Touch'
 | 'Vibration'
 | 'VirtualKeyboard'
 | 'VirtualViewport'
 | 'WebAnimations'
 | 'WebAudio'
 | 'WebAuthentication'
 | 'WebCrypto'
 | 'WebMIDI'
 | 'WebShare'
 | 'WebSpeech'
 | 'WebStorage'
 | 'WebUSB'
 | 'WebWorker'
 | 'WebCodecs'
 | 'WebGL'
 | 'WebGPU'
 | 'WebHID'
 | 'WebRTC'
 | 'WebSocket'
 | 'WebVTT'
 | 'WebXR'
 | 'WindowControlsOverlay'
 | 'XMLHttpRequest';

export type WebApiSource = 'window' | 'navigator' | 'document' | 'screen';

export type WebApiMapper = {
  source: WebApiSource;
  path: string;
  checker?: undefined;
} | {
  source?: undefined;
  path?: undefined;
  checker: () => boolean | Promise<boolean>;
};
